In [20]:

import os
os.getcwd()
os.chdir("/gradution project")
os.getcwd()

'e:\\gradution project'

In [21]:
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

from src.similarity_model import preprocess_dataset
from src.similarity_model import train_embedding_engine
from src.similarity_model import search_by_text
from src.similarity_model import find_similar_projects

print("All modules imported successfully")

All modules imported successfully

In [22]:
file_path = r"E:\gradution project\Data\raw\Graduation Projects - Sheet1.xlsx"

df_raw = pd.read_excel(file_path)

print("Rows:", len(df_raw))
df_raw.tail()

Rows: 301

,ID,Submitted At,Title,Student Names,Supervisor,Year,Category,Technologies,Keywords,Abstract,Description,Problem Statement,Proposed Solution,Objectives,ai summary
296,OCR_36,NaT,Find Missing people using Face Recognition,NaN,Dr. Mai Kamal,2023,surveillance,"kotlin, python flask","artificial intelligence, machine learning, dee...","Our project ""Find Missed People Using Face Rec...",The problem of missing persons and children is...,• The absence of a dedicated digital system fo...,"Our project ""Find Missed People Using Face Rec...",• Develop a user-friendly application accessib...,"This graduation project, titled ""Find Missing ..."
297,OCR_37,NaT,Remember Me Early diagnosis of Alzheimer's dis...,NaN,Dr. Mostafa Elgendy,2023,medical,"dart, flutter, HTML, css, js, php, mvc approac...","healthcare, medical diagnosis, patient care, m...","According to the WHO, around 50 million people...","In this project, we aimed to collect all the t...",• The absence of a dedicated digital system fo...,"According to the WHO, around 50 million people...",• Develop a user-friendly application accessib...,"This graduation project, titled ""Remember Me E..."
298,OCR_40,NaT,Mobile Based System for Traffic Monitoring and...,NaN,Dr. Sahr fawzy,2012,General,Android,"general, software system, graduation project, ...",The theme of the system/application is the usa...,No one can ignore the fact that traffic proble...,• The absence of a dedicated digital system fo...,The theme of the system/application is the usa...,• Develop a user-friendly application accessib...,"This graduation project, titled ""Mobile Based ..."
299,OCR_41,NaT,Detecting Diseases Using Chatbot and Booking C...,NaN,Dr. Shadia Sarhan,2024,medical,"php, laravel, mysql, mvc, livewire package, ui...","healthcare, medical diagnosis, patient care, m...",A Project aim to create application that conta...,Many pcople find difficult to search for docto...,• The absence of a dedicated digital system fo...,A Project aim to create application that conta...,• Develop a user-friendly application accessib...,"This graduation project, titled ""Detecting Dis..."
300,OCR_46,NaT,Electronic School,NaN,Dr. Shaker Elsabagh,2022,Education,"html, css, JavaScript, jquery, bootstrap, api","e-learning, education platform, student manage...",Human history is observing a very strange time...,The world we live in has been through a lot of...,• The absence of a dedicated digital system fo...,Human history is observing a very strange time...,• Achieve accurate and reliable detection/diag...,"This graduation project, titled ""Electronic Sc..."

In [23]:
clean_df = preprocess_dataset(df_raw)

print("Rows after cleaning:", len(clean_df))
clean_df.tail()

2026-05-09 03:44:02,005 | INFO | Starting preprocessing...
2026-05-09 03:44:02,126 | INFO | Removed duplicates: 7
2026-05-09 03:44:02,137 | INFO | Extracting features...
2026-05-09 03:47:15,627 | INFO | Final rows: 294

Rows after cleaning: 294

,id,submitted_at,title,student_names,supervisor,year,category,technologies,keywords,abstract,description,problem_statement,proposed_solution,objectives,ai_summary,project_title,full_content,clean_text,word_count,features
289,OCR_36,NaT,Find Missing people using Face Recognition,NaN,Dr. Mai Kamal,2023,surveillance,"kotlin, python flask","artificial intelligence, machine learning, dee...","Our project ""Find Missed People Using Face Rec...",The problem of missing persons and children is...,• The absence of a dedicated digital system fo...,"Our project ""Find Missed People Using Face Rec...",• Develop a user-friendly application accessib...,"This graduation project, titled ""Find Missing ...",,". . Our project ""Find Missed People Using Face...",. . our project find missed people using face ...,451,"[missing person face, facial recognition techn..."
290,OCR_37,NaT,Remember Me Early diagnosis of Alzheimer's dis...,NaN,Dr. Mostafa Elgendy,2023,medical,"dart, flutter, HTML, css, js, php, mvc approac...","healthcare, medical diagnosis, patient care, m...","According to the WHO, around 50 million people...","In this project, we aimed to collect all the t...",• The absence of a dedicated digital system fo...,"According to the WHO, around 50 million people...",• Develop a user-friendly application accessib...,"This graduation project, titled ""Remember Me E...",,". . According to the WHO, around 50 million pe...",. . according to the who around 50 million peo...,478,"[alzheimer disease ad, delay alzheimer symptom..."
291,OCR_40,NaT,Mobile Based System for Traffic Monitoring and...,NaN,Dr. Sahr fawzy,2012,General,Android,"general, software system, graduation project, ...",The theme of the system/application is the usa...,No one can ignore the fact that traffic proble...,• The absence of a dedicated digital system fo...,The theme of the system/application is the usa...,• Develop a user-friendly application accessib...,"This graduation project, titled ""Mobile Based ...",,. . The theme of the system/application is the...,. . the theme of the system/application is the...,369,"[location based alternatives, roads provides u..."
292,OCR_41,NaT,Detecting Diseases Using Chatbot and Booking C...,NaN,Dr. Shadia Sarhan,2024,medical,"php, laravel, mysql, mvc, livewire package, ui...","healthcare, medical diagnosis, patient care, m...",A Project aim to create application that conta...,Many pcople find difficult to search for docto...,• The absence of a dedicated digital system fo...,A Project aim to create application that conta...,• Develop a user-friendly application accessib...,"This graduation project, titled ""Detecting Dis...",,. . A Project aim to create application that c...,. . a project aim to create application that c...,310,"[doctors users chatbot, disease symptom paragr..."
293,OCR_46,NaT,Electronic School,NaN,Dr. Shaker Elsabagh,2022,Education,"html, css, JavaScript, jquery, bootstrap, api","e-learning, education platform, student manage...",Human history is observing a very strange time...,The world we live in has been through a lot of...,• The absence of a dedicated digital system fo...,Human history is observing a very strange time...,• Achieve accurate and reliable detection/diag...,"This graduation project, titled ""Electronic Sc...",,. . Human history is observing a very strange ...,. . human history is observing a very strange ...,511,"[learning electronic school, online learning p..."

In [24]:
print(type(clean_df.loc[0, "features"]))
print(clean_df.loc[0, "features"])

<class 'list'>
['payment disputes service', 'secure intelligent service', 'technician recommendation module', 'maintain trust marketplace', 'escrow released technicians', 'customers qualified', 'manage account verification', 'service completion confirmed', 'workflow aims', 'feature rule based']

In [25]:
print(clean_df.columns.tolist())

['id', 'submitted_at', 'title', 'student_names', 'supervisor', 'year', 'category', 'technologies', 'keywords', 'abstract', 'description', 'problem_statement', 'proposed_solution', 'objectives', 'ai_summary', 'project_title', 'full_content', 'clean_text', 'word_count', 'features']

In [26]:
object_cols = clean_df.select_dtypes(include="object").columns

for col in object_cols:
    clean_df[col] = clean_df[col].astype(str)

C:\Users\yossef\AppData\Local\Temp\ipykernel_14992\1799785526.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = clean_df.select_dtypes(include="object").columns

In [27]:
clean_df.to_parquet("Data/processed/projects_clean.parquet", index=False)
clean_df.to_csv("Data/processed/projects_clean.csv", index=False)

print("Saved cleaned dataset")

Saved cleaned dataset

In [28]:
engine = train_embedding_engine(
    data_path="Data/processed/projects_clean.parquet"
)

print("Embedding trained successfully")

2026-05-09 03:47:15,851 | INFO | Loading processed dataset...
2026-05-09 03:47:15,897 | INFO | Loading embedding model: all-MiniLM-L6-v2
2026-05-09 03:47:15,898 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2026-05-09 03:47:26,117 | INFO | Use pytorch device_name: cpu
2026-05-09 03:47:26,122 | INFO | Generating embeddings for 294 projects...

Batches:   0%|          | 0/5 [00:00<?, ?it/s]

2026-05-09 03:47:40,263 | INFO | FAISS index built successfully with 294 vectors.
2026-05-09 03:47:40,294 | INFO | Artifacts saved to models
2026-05-09 03:47:40,295 | INFO | Embedding engine completed successfully.

Embedding trained successfully

In [29]:
from importlib import reload
import src.similarity_model as fs

reload(fs)

In [30]:
from importlib import reload
import src.similarity_model as sim

reload(sim)

In [31]:
final_results = find_similar_projects(
    title="Smart Library app",
    description="""
    Library chatbot book recommendation search engine 
    """,
    top_k=5
)
final_results

2026-05-09 03:47:40,400 | INFO | Loading models and artifacts...
2026-05-09 03:47:40,403 | INFO | Loading model: all-MiniLM-L6-v2
2026-05-09 03:47:40,404 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f493475b-2e06-4bce-b590-67ca67d747aa)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/README.md
2026-05-09 03:47:53,875 | WARNING | '(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f493475b-2e06-4bce-b590-67ca67d747aa)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/README.md
Retrying in 1s [Retry 1/5].
2026-05-09 03:47:53,875 | WARNING | Retrying in 1s [Retry 1/5].
2026-05-09 03:47:57,229 | INFO | Use pytorch device_name: cpu
2026-05-09 03:47:57,233 | INFO | Loading FAISS index...
2026-05-09 03:47:57,242 | INFO | Loading feature model: all-MiniLM-L6-v2
2026-05-09 03:47:57,243 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2026-05-09 03:47:59,435 | INFO | Use pytorch device_name: cpu
2026-05-09 03:47:59,438 | INFO | Loading metadata...
2026-05-09 03:47:59,466 | INFO | Preparing query...
2026-05-09 03:47:59,529 | INFO | Running semantic retrieval...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-05-09 03:47:59,588 | INFO | Running hybrid ranking...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

,project_id,project_title,semantic_score,feature_score,coverage,hybrid_score,originality_score,confidence_score,duplicate_risk,shared_features_count,matched_features,unique_query_features,unique_candidate_features,query_features_used,query_clean_text
0,202,,0.6151,0.5655,0.1,0.6027,0.4978,0.4922,Medium,1,"[{'feature_a': 'chatbot book recommendation', ...","[library chatbot book, app library chatbot, li...","[library systems egypt, collaborative reading ...","[library chatbot book, app library chatbot, li...",smart library app. smart library app. library ...
1,1,,0.4137,0.6019,0.1,0.4846,0.5923,0.4262,Low,1,"[{'feature_a': 'library chatbot', 'feature_b':...","[library chatbot book, app library chatbot, ch...","[doctors users chatbot, help patients nearest,...","[library chatbot book, app library chatbot, li...",smart library app. smart library app. library ...
2,225,,0.4159,0.5088,0.1,0.4534,0.6173,0.3899,Low,1,"[{'feature_a': 'library chatbot', 'feature_b':...","[library chatbot book, app library chatbot, ch...","[websites features ai, tourists visiting egypt...","[library chatbot book, app library chatbot, li...",smart library app. smart library app. library ...
3,29,,0.3846,0.5648,0.1,0.4527,0.6178,0.3998,Low,1,"[{'feature_a': 'library chatbot', 'feature_b':...","[library chatbot book, app library chatbot, ch...","[reading managing computer, books intuitive in...","[library chatbot book, app library chatbot, li...",smart library app. smart library app. library ...
4,183,,0.3346,0.6019,0.1,0.4332,0.6334,0.3946,Low,1,"[{'feature_a': 'library chatbot', 'feature_b':...","[library chatbot book, app library chatbot, ch...","[islam mirath calculator, islamic inheritance ...","[library chatbot book, app library chatbot, li...",smart library app. smart library app. library ...

In [32]:
! python -m src.similarity_model.evaluation

==============================
SELF RETRIEVAL TEST
==============================
Projects Tested : 20
Top1 Accuracy   : 100.00%
==============================

==============================
REAL QUERY TEST
==============================

Query: AI Clinic Management System
Top Match:
Score: 0.6201
Risk: Medium

Query: Smart Library Assistant
Top Match:
Score: 0.6127
Risk: Medium

Query: Attendance Face Recognition
Top Match:
Score: 0.6796
Risk: Medium

Query: E-commerce Recommendation Platform
Top Match:
Score: 0.5985
Risk: Medium

==============================
Average Query Score: 0.6277
==============================

==============================
FINAL MODEL STATUS
==============================
VERY GOOD ✅
Overall Score: 0.8511
==============================

2026-05-09 03:48:08,243 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 396bd896-b6ff-4645-a377-6950f068eab0)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json
2026-05-09 03:48:18,553 | WARNING | '(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 396bd896-b6ff-4645-a377-6950f068eab0)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json
Retrying in 1s [Retry 1/5].
2026-05-09 03:48:18,553 | WARNING | Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 7211a374-1e2e-41f0-924c-d68ebbe389e6)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json
2026-05-09 03:48:29,876 | WARNING | '(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 7211a374-1e2e-41f0-924c-d68ebbe389e6)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json
Retrying in 2s [Retry 2/5].
2026-05-09 03:48:29,876 | WARNING | Retrying in 2s [Retry 2/5].
2026-05-09 03:48:42,058 | INFO | Use pytorch device_name: cpu
2026-05-09 03:48:42,064 | INFO | Loading faiss with AVX2 support.
2026-05-09 03:48:42,089 | INFO | Successfully loaded faiss with AVX2 support.
2026-05-09 03:48:42,105 | INFO | Loading metadata...
2026-05-09 03:48:42,167 | INFO | Loading models and artifacts...
2026-05-09 03:48:42,167 | INFO | Loading model: all-MiniLM-L6-v2
2026-05-09 03:48:42,167 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2026-05-09 03:48:45,345 | INFO | Use pytorch device_name: cpu
2026-05-09 03:48:45,347 | INFO | Loading FAISS index...
2026-05-09 03:48:45,347 | INFO | Loading feature model: all-MiniLM-L6-v2
2026-05-09 03:48:45,348 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2026-05-09 03:48:47,664 | INFO | Use pytorch device_name: cpu
2026-05-09 03:48:47,665 | INFO | Preparing query...
2026-05-09 03:48:51,925 | INFO | Running semantic retrieval...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
2026-05-09 03:48:52,023 | INFO | Running hybrid ranking...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 36.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.89it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 33.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 35.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 58.98it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 33.82it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.80it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 35.63it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.85it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 36.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 34.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.78it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 51.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.81it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 34.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 33.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 39.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.93it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.82it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.78it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.98it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.69it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.88it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 18.83it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 29.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 34.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.85it/s]
2026-05-09 03:48:53,383 | INFO | Loading models and artifacts...
2026-05-09 03:48:53,383 | INFO | Preparing query...
2026-05-09 03:48:54,220 | INFO | Running semantic retrieval...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
2026-05-09 03:48:54,446 | INFO | Running hybrid ranking...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 34.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 32.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.65it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 33.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.98it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.86it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.92it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.69it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.64it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 37.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.71it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 49.66it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 49.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 39.79it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 39.86it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.68it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 35.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 37.63it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 36.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 53.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.66it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.88it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 53.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.79it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 52.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 36.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.99it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.82it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.81it/s]
2026-05-09 03:48:55,553 | INFO | Loading models and artifacts...
2026-05-09 03:48:55,553 | INFO | Preparing query...
2026-05-09 03:48:56,471 | INFO | Running semantic retrieval...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 13.93it/s]
2026-05-09 03:48:56,561 | INFO | Running hybrid ranking...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 35.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 37.85it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.99it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 39.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.71it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 59.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.65it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.95it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 37.76it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 52.77it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 36.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.74it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.74it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.99it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.67it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 36.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.91it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.78it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.78it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.78it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 37.68it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.72it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.76it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 52.77it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 35.67it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.10it/s]
2026-05-09 03:48:57,663 | INFO | Loading models and artifacts...
2026-05-09 03:48:57,663 | INFO | Preparing query...
2026-05-09 03:48:58,098 | INFO | Running semantic retrieval...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.86it/s]
2026-05-09 03:48:58,177 | INFO | Running hybrid ranking...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.77it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 36.74it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.75it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.75it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.72it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.71it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 53.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.83it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.76it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 49.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.68it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 52.80it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.78it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.72it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 56.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 37.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.81it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.77it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 52.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.76it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]